CREATE DATABASE ORG;
SHOW DATABASES;
USE ORG;

CREATE TABLE worker(
	WORKER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME CHAR(25),
    LAST_NAME CHAR(25),
    SALARY INT(15),
    JOINING_DATE DATETIME,
    DEPARTMENT CHAR(25)
);

INSERT INTO worker 
(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
(001,'GURU','KAMAT','100000','24-01-24 09.00.00','HR'),
(002,'MEHEK','JAIN','1000000','01-01-24 09.00.00','AI'),
(003,'ROCHAN','BACHARI','100000','24-01-24 09.00.00','HR');

INSERT INTO worker 
(WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT) VALUES
(004,'AKASH','KAMBLE','20000','19-01-24 09.00.00','WD'),
(005,'DIKSHIT','N','900900','24-10-24 09.00.00','AI');

SELECT* FROM worker;

CREATE TABLE Bonus(
	WORKER_REF_ID INT ,
    BONUS_AMOUNT INT(15),
    BONUS_DATE DATETIME,
    FOREIGN KEY (WORKER_REF_ID )
    REFERENCES worker(WORKER_ID)
    ON DELETE CASCADE
);
	
INSERT INTO Bonus 
(WORKER_REF_ID, BONUS_AMOUNT, BONUS_DATE) VALUES
(001,'1000','24-01-24'),
(002,'1000','01-01-24'),
(003,'1000','24-01-24');

CREATE TABLE Title(
	WORKER_REF_ID INT ,
    WORKER_TITLE CHAR(25),
    AFFECTED_FROM DATETIME,
    FOREIGN KEY (WORKER_REF_ID)
     REFERENCES worker(WORKER_ID)
	 ON DELETE CASCADE
);

INSERT INTO Title
(WORKER_REF_ID, WORKER_TITLE, AFFECTED_FROM) VALUES
(001,'MANAGER','24-01-24 09.00.00'),
(002,'EMPLOYEE','01-01-24 09.00.00'),
(003,'MANAGER','24-01-24 09.00.00');

SELECT FIRST_NAME,SALARY FROM worker;

SELECT *FROM worker WHERE Salary>100000;
		
SELECT *FROM worker WHERE DEPARTMENT= 'HR';

SELECT *FROM worker WHERE SALARY BETWEEN 10000 AND 300000;

SELECT *FROM worker WHERE DEPARTMENT = 'HR' OR DEPARTMENT = 'AI';

SELECT *FROM worker WHERE DEPARTMENT IN ('HR','AI');

SELECT *FROM worker where DEPARTMENT NOT IN ('HR');

select *from worker order by SALARY DESC;

-- AVG salary per dep
select DEPARTMENT, avg(salary) from worker group by DEPARTMENT;

-- Min 
select DEPARTMENT, min(salary) from worker group by DEPARTMENT;

-- Max
select DEPARTMENT, max(salary) from worker group by DEPARTMENT;

-- Group by having
select DEPARTMENT, count(DEPARTMENT) from worker group by DEPARTMENT having count(DEPARTMENT)>1;

